### ISSUE TITLE
invalid DOM Nesting

### ISSUE THREAD

**Issue by ctownshend** [sonatype-nexus-community/nexus-iq-chrome-extension#270]
react-dom.development.js:86 Warning: validateDOMNesting(...): <h2> cannot appear as a descendant of <p>.
    at h2
    at chrome-extension://aikamalnmhgcjndldaoakdjomheehhhb/static/js/main.js:35685:31
    at div
    at NxVulnerabilityDetails (chrome-extension://aikamalnmhgcjndldaoakdjomheehhhb/static/js/main.js:26422:35)
    at VulnDetails (chrome-extension://aikamalnmhgcjndldaoakdjomheehhhb/static/js/main.js:121579:75)
    at p
    at div
    at details
    at NxAccordion (chrome-extension://aikamalnmhgcjndldaoakdjomheehhhb/static/js/main.js:14635:27)
    at SecurityItemDisplay (chrome-extension://aikamalnmhgcjndldaoakdjomheehhhb/static/js/main.js:121539:75)
    at section
    at div
    at SecurityPage (chrome-extension://aikamalnmhgcjndldaoakdjomheehhhb/static/js/main.js:121613:76)
    at div
    at NxTabPanelElement (chrome-extension://aikamalnmhgcjndldaoakdjomheehhhb/static/js/main.js:23586:63)
    at div
    at NxTabsElement (chrome-extension://aikamalnmhgcjndldaoakdjomheehhhb/static/js/main.js:23651:27)
    at div
    at section
    at Popup (chrome-extension://aikamalnmhgcjndldaoakdjomheehhhb/static/js/main.js:121745:90)
    at main
    at div
    at NexusChromeExtensionContainer (chrome-extension://aikamalnmhgcjndldaoakdjomheehhhb/static/js/main.js:120572:9)

**Comment by ctownshend** [comment]
fixed by removing paragraph element
